<?xml version="1.0"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.16</version>
        <relativePath/>
    </parent>

    <groupId>fi.fmi.avi.archiver</groupId>
    <artifactId>aviation-message-archiver</artifactId>
    <version>1.4.2-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Aviation message archiver</name>
    <description>
        A service application for operationally archiving aviation weather messages into database.
    </description>

    <url>https://github.com/fmidev/aviation-message-archiver</url>
    <organization>
        <name>FMI OpenSource community</name>
        <url>https://ilmatieteenlaitos.fi</url>
    </organization>

    <licenses>
        <license>
            <comments>
                Copyright (c) 2019 Finnish Meteorological Institute

                Permission is hereby granted, free of charge, to any person obtaining a copy
                of this software and associated documentation files (the "Software"), to deal
                in the Software without restriction, including without limitation the rights
                to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
                copies of the Software, and to permit persons to whom the Software is
                furnished to do so, subject to the following conditions:

                The above copyright notice and this permission notice shall be included in all
                copies or substantial portions of the Software.

                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
                FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
                AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
                LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
                OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
                SOFTWARE.
            </comments>
            <distribution>repo</distribution>
            <name>MIT License</name>
            <url/>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/fmidev/aviation-message-archiver.git</connection>
        <developerConnection>scm:git:https://github.com/fmidev/aviation-message-archiver.git</developerConnection>
        <url>https://github.com/fmidev/aviation-message-archiver</url>
        <tag>HEAD</tag>
    </scm>

    <!-- Two-phase release to GitHub as defined at http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github-->
    <distributionManagement>
        <repository>
            <id>internal.repo</id>
            <name>Temporary Staging Repository</name>
            <url>file://${project.build.directory}/mvn-repo</url>
        </repository>
    </distributionManagement>

    <properties>
        <java.version>21</java.version>
        <argLine/>

        <!-- Custom Maven release repository properties -->
        <project.scm.id>github</project.scm.id>
        <github-repo-owner>fmidev</github-repo-owner>
        <github.global.server>github</github.global.server>
        <github-mvn-release-repo>fmi-os-mvn-repo</github-mvn-release-repo>
        <github-mvn-snapshot-repo>fmi-os-mvn-snapshot-repo</github-mvn-snapshot-repo>
        <github-site-maven-plugin.version>0.12</github-site-maven-plugin.version>

        <!-- The spring-boot.version property is used in documentation links in README.md -->
        <spring-boot.version>${project.parent.version}</spring-boot.version>
        <auto-value.version>1.11.1</auto-value.version>
        <avidb-schema.version>1.0.0</avidb-schema.version>
        <netty4.version>4.2.17.Final</netty4.version>

        <avidb-schema.branch-rawname>avidb-schema-${avidb-schema.version}</avidb-schema.branch-rawname>

        <spring-boot.repackage.classifier>bundle</spring-boot.repackage.classifier>

        <doclint>all,-missing</doclint>

        <doc.msg.generated>Generated - DO NOT EDIT! Instead, edit sources under src/doc directory.</doc.msg.generated>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>fi.fmi.avi.converter</groupId>
                <artifactId>fmi-avi-messageconverter-bom</artifactId>
                <version>4.1.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava-bom</artifactId>
                <version>33.7.1-jre</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-bom</artifactId>
                <version>3.27.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Once you’re done with the migration, please make sure to remove this module from your project’s dependencies.
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-properties-migrator</artifactId>
            <scope>runtime</scope>
        </dependency>
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.13</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>2.4.240</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-file</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
        <dependency>
            <groupId>com.rabbitmq.client</groupId>
            <artifactId>amqp-client</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.inferred</groupId>
            <artifactId>freebuilder</artifactId>
            <version>2.7.0</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.google.auto.value</groupId>
            <artifactId>auto-value-annotations</artifactId>
            <version>${auto-value.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.auto.value</groupId>
            <artifactId>auto-value</artifactId>
            <version>${auto-value.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>fi.fmi.avi.converter</groupId>
            <artifactId>fmi-avi-messageconverter</artifactId>
        </dependency>
        <dependency>
            <groupId>fi.fmi.avi.converter</groupId>
            <artifactId>fmi-avi-messageconverter-tac</artifactId>
        </dependency>
        <dependency>
            <groupId>fi.fmi.avi.converter</groupId>
            <artifactId>fmi-avi-messageconverter-iwxxm</artifactId>
        </dependency>
        <dependency>
            <groupId>fi.fmi.avi.avidb</groupId>
            <artifactId>avidb-schema</artifactId>
            <version>${avidb-schema.version}</version>
        </dependency>

        <!-- QPid dependencies -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>${netty4.version}</version>
            <classifier>linux-x86_64</classifier>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <version>${netty4.version}</version>
            <classifier>osx-x86_64</classifier>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-io_uring</artifactId>
            <version>${netty4.version}</version>
            <classifier>linux-x86_64</classifier>
            <scope>runtime</scope>
        </dependency>
        <!-- End of QPid dependencies -->

        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>7.2</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-testlib</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>xmlunit</groupId>
            <artifactId>xmlunit</artifactId>
            <version>1.6</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.threeten</groupId>
            <artifactId>threeten-extra</artifactId>
            <version>1.10.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.github.github</groupId>
                    <artifactId>site-maven-plugin</artifactId>
                    <version>${github-site-maven-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
                <configuration>
                    <includeOnlyProperties>
                        <includeOnlyProperty><![CDATA[^git\.(branch|dirty|tag|tags)$]]></includeOnlyProperty>
                        <includeOnlyProperty><![CDATA[^git\.build\.(time|version)$]]></includeOnlyProperty>
                        <includeOnlyProperty><![CDATA[^git\.commit\.(id.*|time)$]]></includeOnlyProperty>
                    </includeOnlyProperties>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-resources</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                        <configuration>
                            <delimiters>
                                <delimiter>@</delimiter>
                            </delimiters>
                            <useDefaultDelimiters>false</useDefaultDelimiters>
                        </configuration>
                    </execution>
                    <execution>
                        <id>docs</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.basedir}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/doc</directory>
                                    <includes>
                                        <include>README.md</include>
                                        <include>compose.yaml</include>
                                        <include>aviation-message-archiver.container</include>
                                    </includes>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                            <encoding>UTF-8</encoding>
                            <useDefaultDelimiters>true</useDefaultDelimiters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>dependency-properties</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>add-integration-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/test-integration/java</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-integration-test-resource</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>src/test-integration/resources</directory>
                                    <targetPath>${maven.test.dest}</targetPath>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-helper-regex-artifact-branch-rawnames</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>regex-properties</goal>
                        </goals>
                        <configuration>
                            <regexPropertySettings>
                                <regexPropertySetting>
                                    <name>fmi-avi-messageconverter.branch-rawname</name>
                                    <value>${fi.fmi.avi.converter:fmi-avi-messageconverter:jar}</value>
                                    <regex>
                                        ^.*(fmi-avi-messageconverter-[0-9\.]+(-beta[0-9]+)?(-SNAPSHOT)?)\.jar.*$
                                    </regex>
                                    <replacement>$1</replacement>
                                    <failIfNoMatch>true</failIfNoMatch>
                                </regexPropertySetting>
                                <regexPropertySetting>
                                    <name>fmi-avi-messageconverter-iwxxm.branch-rawname</name>
                                    <value>${fi.fmi.avi.converter:fmi-avi-messageconverter-iwxxm:jar}</value>
                                    <regex>
                                        ^.*(fmi-avi-messageconverter-iwxxm-[0-9\.]+(-beta[0-9]+)?(-SNAPSHOT)?)\.jar.*$
                                    </regex>
                                    <replacement>$1</replacement>
                                    <failIfNoMatch>true</failIfNoMatch>
                                </regexPropertySetting>
                                <regexPropertySetting>
                                    <name>fmi-avi-messageconverter-tac.branch-rawname</name>
                                    <value>${fi.fmi.avi.converter:fmi-avi-messageconverter-tac:jar}</value>
                                    <regex>
                                        ^.*(fmi-avi-messageconverter-tac-[0-9\.]+(-beta[0-9]+)?(-SNAPSHOT)?)\.jar.*$
                                    </regex>
                                    <replacement>$1</replacement>
                                    <failIfNoMatch>true</failIfNoMatch>
                                </regexPropertySetting>
                            </regexPropertySettings>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-helper-regex-artifact-branch-names</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>regex-properties</goal>
                        </goals>
                        <configuration>
                            <regexPropertySettings>
                                <regexPropertySetting>
                                    <name>fmi-avi-messageconverter.branch-name</name>
                                    <value>${fmi-avi-messageconverter.branch-rawname}</value>
                                    <regex>^.*-SNAPSHOT$</regex>
                                    <replacement>main</replacement>
                                    <failIfNoMatch>false</failIfNoMatch>
                                </regexPropertySetting>
                                <regexPropertySetting>
                                    <name>fmi-avi-messageconverter-iwxxm.branch-name</name>
                                    <value>${fmi-avi-messageconverter-iwxxm.branch-rawname}</value>
                                    <regex>^.*-SNAPSHOT$</regex>
                                    <replacement>main</replacement>
                                    <failIfNoMatch>false</failIfNoMatch>
                                </regexPropertySetting>
                                <regexPropertySetting>
                                    <name>fmi-avi-messageconverter-tac.branch-name</name>
                                    <value>${fmi-avi-messageconverter-tac.branch-rawname}</value>
                                    <regex>^.*-SNAPSHOT$</regex>
                                    <replacement>main</replacement>
                                    <failIfNoMatch>false</failIfNoMatch>
                                </regexPropertySetting>
                                <regexPropertySetting>
                                    <name>avidb-schema.branch-name</name>
                                    <value>${avidb-schema.branch-rawname}</value>
                                    <regex>^.*-SNAPSHOT$</regex>
                                    <replacement>main</replacement>
                                    <failIfNoMatch>false</failIfNoMatch>
                                </regexPropertySetting>
                                <regexPropertySetting>
                                    <name>application.image.tag</name>
                                    <value>${project.version}</value>
                                    <regex>^.*-SNAPSHOT$</regex>
                                    <replacement>main</replacement>
                                    <failIfNoMatch>false</failIfNoMatch>
                                </regexPropertySetting>
                            </regexPropertySettings>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>3.0.0-M6</version>
                <configuration>
                    <!--
                      Generate documentation and include it in SCM. Requires plugin version >=3.
                      https://stackoverflow.com/a/68687685
                    -->
                    <preparationGoals>validate resources:copy-resources@docs scm:add</preparationGoals>
                    <completionGoals>validate resources:copy-resources@docs scm:add</completionGoals>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-scm-plugin</artifactId>
                <version>2.2.1</version>
                <configuration>
                    <includes>README.md,compose.yaml,aviation-message-archiver.container</includes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                            <goal>build-info</goal>
                        </goals>
                        <configuration>
                            <classifier>${spring-boot.repackage.classifier}</classifier>
                            <mainClass>fi.fmi.avi.archiver.AviationMessageArchiver</mainClass>
                            <attach>false</attach>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>fmi-os-release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.github</groupId>
                        <artifactId>site-maven-plugin</artifactId>
                        <configuration>
                            <message>Maven artifacts for ${project.version}</message>  <!-- git commit message -->
                            <noJekyll>true
                            </noJekyll>                                  <!-- disable webpage processing -->
                            <outputDirectory>${project.build.directory}/mvn-repo
                            </outputDirectory> <!-- matches distribution management repository url above -->
                            <branch>refs/heads/master</branch>                       <!-- remote branch name -->
                            <includes>
                                <include>**/*</include>
                            </includes>
                            <repositoryName>${github-mvn-release-repo}</repositoryName>      <!-- github repo name -->
                            <repositoryOwner>${github-repo-owner}</repositoryOwner>    <!-- github username  -->
                            <merge>true</merge>
                        </configuration>
                        <executions>
                            <!-- run site-maven-plugin's 'site' target as part of the build's normal 'release' phase -->
                            <execution>
                                <goals>
                                    <goal>site</goal>
                                </goals>
                                <phase>deploy</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>fmi-os-snapshot</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.github</groupId>
                        <artifactId>site-maven-plugin</artifactId>
                        <configuration>
                            <message>Maven artifacts for ${project.version}</message>  <!-- git commit message -->
                            <noJekyll>true
                            </noJekyll>                                  <!-- disable webpage processing -->
                            <outputDirectory>${project.build.directory}/mvn-repo
                            </outputDirectory> <!-- matches distribution management repository url above -->
                            <branch>refs/heads/master</branch>                       <!-- remote branch name -->
                            <includes>
                                <include>**/*</include>
                            </includes>
                            <repositoryName>${github-mvn-snapshot-repo}</repositoryName>      <!-- github repo name -->
                            <repositoryOwner>${github-repo-owner}</repositoryOwner>    <!-- github username  -->
                            <merge>true</merge>
                        </configuration>
                        <executions>
                            <!-- run site-maven-plugin's 'site' target as part of the build's normal 'deploy' phase -->
                            <execution>
                                <goals>
                                    <goal>site</goal>
                                </goals>
                                <phase>deploy</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
