##############################################
#
#  Aviation Message Archiver
#  =========================
#
#  Development profile default configuration
#
#  Property values surrounded by '@' characters (e.g. '@pom.property@') are references to Maven POM properties,
#  and will be replaced upon build with actual build-time property values.
#
##############################################

##############################################
#
#  Logging properties
#
#  See Spring Boot reference documentation for details.
#  https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging
#
#  Base logging configuration is in src/main/resources/logback-spring.xml
#
##############################################
logging:
  level:
    fi.fmi.avi.archiver: DEBUG
    org.springframework.integration.handler.LoggingHandler: DEBUG
