name: Clean up old container images

on:
  schedule:
    # Run weekly on Tuesday at 01:26 UTC
    - cron: '26 1 * * 2'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup-pre-releases:
    name: Delete old pre-release container images
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Delete old pre-release container images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-untagged: true
          delete-partial-images: true
          older-than: 7 days
          keep-n-tagged: 10
          use-regex: true
          exclude-tags: |
            latest
            main
            \d+(\.\d+)*

  cleanup-old-releases:
    name: Delete old release container images
    needs: cleanup-pre-releases
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Delete old release container images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-tags: \d+(\.\d+)*
          use-regex: true
          keep-n-tagged: 20


